export type ErrorCode = 'VALIDATION_ERROR' | 'UNAUTHORIZED' | 'FORBIDDEN' | 'NOT_FOUND' | 'CONFLICT' | 'IDEMPOTENCY_KEY_REUSED' | 'PAYLOAD_TOO_LARGE' | 'INTERNAL_ERROR' | 'CSRF_ORIGIN_INVALID' | 'CLIENT_VERSION_UNSUPPORTED' | 'ENTITY_NOT_FOUND' | 'WORKSPACE_ACCESS_REVOKED' | 'WORKSPACE_FORBIDDEN' | 'WORKSPACE_MISMATCH' | 'SESSION_EXPIRED' | 'SESSION_REUSED' | 'EMAIL_ALREADY_EXISTS' | 'INVALID_CREDENTIALS' | 'INVITATION_INVALID' | 'INVITATION_RECIPIENT_MISMATCH' | 'LAST_ADMIN_PROTECTED' | 'UPLOAD_ATTEMPT_INVALID' | 'UPLOAD_OFFSET_MISMATCH' | 'ASSET_SIZE_MISMATCH' | 'ASSET_CHECKSUM_MISMATCH' | 'ASSET_TYPE_UNSUPPORTED' | 'DEPENDENCY_NOT_READY' | 'CURSOR_EXPIRED' | 'DEVICE_EXPIRED' | 'BOOTSTRAP_EXPIRED' | 'ID_RETIRED';

export class AppError extends Error {
  constructor(
    readonly statusCode: number,
    readonly code: ErrorCode,
    message: string,
    readonly details?: unknown,
  ) {
    super(message);
    this.name = 'AppError';
  }
}
