import { test } from '@playwright/test';
import { BrowserProfile, ProductionServer } from './helpers';
import { createSong, openOperator, openProjection } from './presentation.helpers';
test('shot', async () => {
  const server = new ProductionServer(); const profile = new BrowserProfile();
  await server.start();
  const context = await profile.open(); const page = await context.newPage();
  await createSong(page, { durations: ['20', '20'] });
  await openOperator(page, { mode: 'preference' });
  const projection = await openProjection(context, page);
  await page.getByRole('button', { name: '▶ Iniciar' }).click();
  await projection.waitForTimeout(2500);
  await projection.screenshot({ path: '/tmp/claude-1000/-home-programador1-projects-LouvorVisual/41ae8aa5-f8fa-43a2-9c88-89c5b7de8fb6/scratchpad/cover-grafite.png' });
  await page.locator('[data-theme="violeta"]').click();
  await projection.waitForTimeout(800);
  await projection.screenshot({ path: '/tmp/claude-1000/-home-programador1-projects-LouvorVisual/41ae8aa5-f8fa-43a2-9c88-89c5b7de8fb6/scratchpad/cover-violeta.png' });
  await page.getByTestId('advance').click();
  await projection.waitForTimeout(250);
  await projection.screenshot({ path: '/tmp/claude-1000/-home-programador1-projects-LouvorVisual/41ae8aa5-f8fa-43a2-9c88-89c5b7de8fb6/scratchpad/mid.png' });
  await projection.waitForTimeout(900);
  await projection.screenshot({ path: '/tmp/claude-1000/-home-programador1-projects-LouvorVisual/41ae8aa5-f8fa-43a2-9c88-89c5b7de8fb6/scratchpad/after.png' });
  await context.close(); await server.stop(); profile.remove();
});
