import express, { type Express, type Request, type Response } from 'express';
import { syncBootstrapPageQuerySchema, syncBootstrapRequestSchema, syncPullQuerySchema, syncPushRequestSchema, uuidSchema, type SyncResult } from '@louvorvisual/contracts';
import { z } from 'zod';
import { errorHandler, notFound } from './middlewares/errors';
import { requestId, type RequestWithId } from './middlewares/requestId';
import { validate } from './middlewares/validate';
import { InMemoryIdentityStore } from './modules/identity/in-memory-identity-store';
import { type IdentityStore, IdentityError, MAX_UPLOAD_CHUNK_BYTES, ROLES, safeUser, type Role } from './modules/identity/identity-store';
import { InMemorySyncStore } from './modules/sync/in-memory-sync-store';
import type { SyncStore } from './modules/sync/sync-store';
import { AppError, type ErrorCode } from './utils/AppError';
import { clientVersionAccepted, readApiConfig } from './config';

type Options = { syncStore?: SyncStore; actorId?: (request: Request) => string | null; identityStore?: IdentityStore };
const workspaceParams = z.strictObject({ workspaceId: uuidSchema });
const assetParams = z.strictObject({ workspaceId: uuidSchema, assetId: uuidSchema });
const memberParams = z.strictObject({ workspaceId: uuidSchema, userId: uuidSchema });
const entityParams = z.strictObject({ workspaceId: uuidSchema, entityId: uuidSchema });
const revisionParams = z.strictObject({ workspaceId: uuidSchema, entityId: uuidSchema, type: z.enum(['song', 'arrangement', 'theme', 'setlist', 'asset']) });
const roleSchema = z.enum(ROLES);
const credentialsSchema = z.strictObject({ email: z.email(), password: z.string().min(12).max(256) });
const registerSchema = credentialsSchema.extend({ name: z.string().trim().min(1).max(200) });
const workspaceSchema = z.strictObject({ name: z.string().trim().min(1).max(200), timezone: z.string().min(1).max(64).default('UTC') });
const inviteSchema = z.strictObject({ email: z.email(), role: roleSchema });
const memberPatchSchema = z.strictObject({ role: roleSchema.optional(), status: z.enum(['active', 'revoked']).optional() }).refine((value) => value.role || value.status, 'empty patch');
const assetSchema = (maxAssetBytes: number) => z.strictObject({ id: uuidSchema, sha256: z.string().regex(/^[0-9a-f]{64}$/), filename: z.string().trim().min(1).max(255), mimeType: z.enum(['audio/mpeg', 'audio/wav']), byteSize: z.int().min(1).max(maxAssetBytes), audioKind: z.enum(['original', 'playback']), durationMs: z.int().min(0).nullable() });
const parseCookies = (req: Request) => Object.fromEntries((req.headers.cookie ?? '').split(';').map((x) => x.trim().split(/=(.*)/s, 2)).filter(([key]) => key).map(([key, value]) => [key, decodeURIComponent(value ?? '')]));
const bearer = (req: Request) => req.header('authorization')?.startsWith('Bearer ') ? req.header('authorization')!.slice(7) : undefined;
const param = (req: Request, key: string) => { const value = req.params[key]; return Array.isArray(value) ? value[0] ?? '' : value ?? ''; };
function reply(res: Response, req: Request, data: unknown, status = 200) { res.status(status).json({ data, requestId: (req as RequestWithId).requestId }); }
function mapIdentity(error: unknown): never { if (error instanceof IdentityError) throw new AppError(error.status, error.code as ErrorCode, error.message); throw error; }
function setCookies(res: Response, accessToken: string, refreshToken: string) { const secure = process.env.NODE_ENV === 'production' ? '; Secure' : ''; res.append('Set-Cookie', [`lv_access=${encodeURIComponent(accessToken)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=900${secure}`, `lv_refresh=${encodeURIComponent(refreshToken)}; HttpOnly; Path=/api/v1/auth; SameSite=Strict; Max-Age=2592000${secure}`]); }

export function createApp(options: Options = {}): Express {
  const config = readApiConfig(); const app = express(); const syncStore = options.syncStore ?? new InMemorySyncStore(); const identity = options.identityStore ?? new InMemoryIdentityStore(); const actorOverride = options.actorId;
  app.disable('x-powered-by'); app.use(requestId); app.use((req, _res, next) => { const version=req.header('x-louvorvisual-client-version'); if(version&&!clientVersionAccepted(version,config)) return next(new AppError(426,'CLIENT_VERSION_UNSUPPORTED','Versão do cliente fora da janela compatível.',{ min:config.minClientVersion,max:config.maxClientVersion })); next(); }); app.use(express.json({ limit: '2mb', type: 'application/json' }));
  app.get('/health', (req, res) => reply(res, req, { status: 'ok' }));
  const user = (req: Request) => identity.authenticate(bearer(req) ?? parseCookies(req).lv_access);
  const requireUser = async (req: Request) => { const current = await user(req); if (!current) throw new AppError(401, 'UNAUTHORIZED', 'Não autenticado.'); return current; };
  const csrf = (req: Request) => { const cookies = parseCookies(req); if (!bearer(req) && cookies.lv_access) { const origin = req.header('origin'); if (!origin || (config.publicOrigin && origin !== config.publicOrigin)) throw new AppError(403, 'CSRF_ORIGIN_INVALID', 'Origem não autorizada.'); } };
  const access = async (req: Request, workspaceId: string, roles: Role[]) => { if (actorOverride) { const id = actorOverride(req); if (!id) throw new AppError(401, 'UNAUTHORIZED', 'Não autenticado.'); return id; } try { const current = await requireUser(req); await identity.requireRole(workspaceId, current.id, roles); return current.id; } catch (error) { return mapIdentity(error); } };

  app.post('/api/v1/auth/register', validate({ body: registerSchema }), async (req, res, next) => { try { csrf(req); const u = await identity.register(req.body.name, req.body.email, req.body.password); const t = await identity.issue(u.id); setCookies(res, t.accessToken, t.refreshToken); reply(res, req, { user: safeUser(u), accessToken: t.accessToken }, 201); } catch (e) { next(e); } });
  app.post('/api/v1/auth/login', validate({ body: credentialsSchema }), async (req, res, next) => { try { csrf(req); const u = await identity.login(req.body.email, req.body.password); const t = await identity.issue(u.id); setCookies(res, t.accessToken, t.refreshToken); reply(res, req, { user: safeUser(u), accessToken: t.accessToken }); } catch (e) { next(e); } });
  app.post('/api/v1/auth/refresh', async (req, res, next) => { try { csrf(req); const t = await identity.refresh(parseCookies(req).lv_refresh ?? req.body?.refreshToken ?? ''); setCookies(res, t.accessToken, t.refreshToken); reply(res, req, { accessToken: t.accessToken }); } catch (e) { next(e); } });
  app.post('/api/v1/auth/logout', async (req, res, next) => { try { csrf(req); await identity.logout(parseCookies(req).lv_refresh ?? req.body?.refreshToken); res.append('Set-Cookie', ['lv_access=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax', 'lv_refresh=; HttpOnly; Path=/api/v1/auth; Max-Age=0; SameSite=Strict']); reply(res, req, { loggedOut: true }); } catch (e) { next(e); } });
  app.get('/api/v1/auth/me', async (req, res, next) => { try { const u = await requireUser(req); reply(res, req, { user: safeUser(u), workspaces: await identity.listWorkspaces(u.id) }); } catch (e) { next(e); } });
  app.post('/api/v1/workspaces', validate({ body: workspaceSchema }), async (req, res, next) => { try { csrf(req); const u = await requireUser(req); const workspace = await identity.createWorkspace(u.id, req.body.name, req.body.timezone); await syncStore.ensureWorkspace?.(workspace); reply(res, req, workspace, 201); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces', async (req, res, next) => { try { reply(res, req, await identity.listWorkspaces((await requireUser(req)).id)); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces/:workspaceId/members', validate({ params: workspaceParams }), async (req, res, next) => { try { const u = await requireUser(req); reply(res, req, await identity.listMembers(param(req, 'workspaceId'), u.id)); } catch (e) { next(e); } });
  app.post('/api/v1/workspaces/:workspaceId/invitations', validate({ params: workspaceParams, body: inviteSchema }), async (req, res, next) => { try { csrf(req); const u = await requireUser(req); reply(res, req, await identity.invite(param(req, 'workspaceId'), u.id, req.body.email, req.body.role), 201); } catch (e) { next(e); } });
  app.post('/api/v1/invitations/:token/accept', validate({ params: z.strictObject({ token: z.string().min(20) }) }), async (req, res, next) => { try { csrf(req); reply(res, req, await identity.acceptInvitation(param(req, 'token'), (await requireUser(req)).id)); } catch (e) { next(e); } });
  app.patch('/api/v1/workspaces/:workspaceId/members/:userId', validate({ params: memberParams, body: memberPatchSchema }), async (req, res, next) => { try { csrf(req); reply(res, req, await identity.updateMember(param(req, 'workspaceId'), (await requireUser(req)).id, param(req, 'userId'), req.body)); } catch (e) { next(e); } });
  app.post('/api/v1/workspaces/:workspaceId/sync/push', validate({ params: workspaceParams, body: syncPushRequestSchema }), async (req, res, next) => { try { csrf(req); const workspaceId = param(req, 'workspaceId'); const actor = await access(req, workspaceId, ['editor', 'admin']); const results: SyncResult[] = []; for (const operation of req.body.operations) {
    if (Buffer.byteLength(JSON.stringify(operation.payload), 'utf8') > 1024 * 1024) { results.push({ opId: operation.opId, status: 'rejected', code: 'PAYLOAD_TOO_LARGE' }); continue; }
    results.push(operation.payload.workspaceId === workspaceId ? await syncStore.apply(workspaceId, actor, operation, req.body.deviceId) : { opId: operation.opId, status: 'rejected', code: 'WORKSPACE_MISMATCH' });
  } reply(res, req, { results }); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces/:workspaceId/sync/pull', validate({ params: workspaceParams, query: syncPullQuerySchema }), async (req, res, next) => { try { const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); reply(res, req, await syncStore.pull(workspaceId, syncPullQuerySchema.parse(req.query).cursor, syncPullQuerySchema.parse(req.query).limit)); } catch (e) { next(e); } });
  app.post('/api/v1/workspaces/:workspaceId/sync/bootstrap', validate({ params: workspaceParams, body: syncBootstrapRequestSchema }), async (req, res, next) => { try { csrf(req); const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); if (!syncStore.bootstrap) throw new AppError(503, 'INTERNAL_ERROR', 'Bootstrap indisponível.'); reply(res, req, await syncStore.bootstrap(workspaceId, req.body.limit)); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces/:workspaceId/sync/bootstrap/:token', validate({ params: z.strictObject({ workspaceId: uuidSchema, token: uuidSchema }), query: syncBootstrapPageQuerySchema }), async (req, res, next) => { try { const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); if (!syncStore.bootstrapPage) throw new AppError(503, 'INTERNAL_ERROR', 'Bootstrap indisponível.'); const query = syncBootstrapPageQuerySchema.parse(req.query); reply(res, req, await syncStore.bootstrapPage(workspaceId, param(req, 'token'), query.cursor, query.limit)); } catch (e) { next(e); } });
  for (const plural of ['songs', 'arrangements', 'themes', 'setlists'] as const) { const type = plural.slice(0, -1) as 'song' | 'arrangement' | 'theme' | 'setlist'; app.get(`/api/v1/workspaces/:workspaceId/${plural}`, validate({ params: workspaceParams }), async (req, res, next) => { try { const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); reply(res, req, await syncStore.list?.(workspaceId, type, 100) ?? []); } catch (e) { next(e); } }); app.get(`/api/v1/workspaces/:workspaceId/${plural}/:entityId`, validate({ params: entityParams }), async (req, res, next) => { try { const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); const entity = await syncStore.get?.(workspaceId, type, param(req, 'entityId')); if (!entity) throw new AppError(404, 'ENTITY_NOT_FOUND', 'Documento não encontrado.'); reply(res, req, entity); } catch (e) { next(e); } }); }
  app.get('/api/v1/workspaces/:workspaceId/revisions/:type/:entityId', validate({ params: revisionParams }), async (req, res, next) => { try { const workspaceId = param(req, 'workspaceId'); await access(req, workspaceId, [...ROLES]); reply(res, req, await syncStore.revisions?.(workspaceId, param(req, 'type') as never, param(req, 'entityId'), 100) ?? []); } catch (e) { next(e); } });
  app.post('/api/v1/workspaces/:workspaceId/assets', validate({ params: workspaceParams, body: assetSchema(config.maxAssetBytes) }), async (req, res, next) => { try { csrf(req); const u = await requireUser(req); const workspaceId = param(req, 'workspaceId'); reply(res, req, await identity.registerAsset(workspaceId, u.id, { ...req.body, workspaceId }), 201); } catch (e) { next(e); } });
  app.put('/api/v1/workspaces/:workspaceId/assets/:assetId/content', express.raw({ type: () => true, limit: config.maxAssetBytes }), validate({ params: assetParams }), async (req, res, next) => { try { csrf(req); const u = await requireUser(req); if (!Buffer.isBuffer(req.body)) throw new AppError(400, 'VALIDATION_ERROR', 'Bytes de áudio obrigatórios.'); reply(res, req, await identity.upload(param(req, 'workspaceId'), u.id, param(req, 'assetId'), req.header('upload-attempt-id'), req.body, req.header('content-type'))); } catch (e) { next(e); } });
  // Envio retomável: cada parte continua de `Upload-Offset`; uma falha repete só a parte que faltou.
  app.patch('/api/v1/workspaces/:workspaceId/assets/:assetId/content', express.raw({ type: () => true, limit: MAX_UPLOAD_CHUNK_BYTES }), validate({ params: assetParams }), async (req, res, next) => { try { csrf(req); const u = await requireUser(req); if (!Buffer.isBuffer(req.body)) throw new AppError(400, 'VALIDATION_ERROR', 'Bytes de áudio obrigatórios.'); const offset = z.coerce.number().int().min(0).safeParse(req.header('upload-offset')); if (!offset.success) throw new AppError(400, 'VALIDATION_ERROR', 'Upload-Offset obrigatório.'); reply(res, req, await identity.uploadChunk(param(req, 'workspaceId'), u.id, param(req, 'assetId'), req.header('upload-attempt-id'), offset.data, req.body, req.header('content-type'))); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces/:workspaceId/assets/:assetId', validate({ params: assetParams }), async (req, res, next) => { try { reply(res, req, await identity.getAsset(param(req, 'workspaceId'), (await requireUser(req)).id, param(req, 'assetId'))); } catch (e) { next(e); } });
  app.get('/api/v1/workspaces/:workspaceId/assets/:assetId/content', validate({ params: assetParams }), async (req, res, next) => { try { const u = await requireUser(req); const workspaceId = param(req, 'workspaceId'); const assetId = param(req, 'assetId'); const asset = await identity.getAsset(workspaceId, u.id, assetId); const bytes = await identity.content(workspaceId, u.id, assetId); res.set({ 'Cache-Control': 'private, no-store', 'Content-Type': asset.mimeType }).status(200).send(bytes); } catch (e) { next(e); } });
  app.delete('/api/v1/workspaces/:workspaceId/assets/:assetId', validate({ params: assetParams }), async (req, res, next) => { try { csrf(req); await identity.deleteAsset(param(req, 'workspaceId'), (await requireUser(req)).id, param(req, 'assetId')); reply(res, req, { deleted: true }); } catch (e) { next(e); } });
  app.use(notFound); app.use(errorHandler); return app;
}
